atomicjolt/lti_starter_app

app/controllers/api/applications_controller.rb, client/js/_admin/actions/applications.js, client/js/_admin/components/applications/modal.jsx
This fixes the modal that edits application settings.
=> Fix applications modal

client/js/_admin/components/lti_installs/index.jsx, client/js/_admin/components/lti_installs/sidebar.jsx
Fix setting application to be sent into sidebar
=> Add modal to edit app instance

app/controllers/api/sites_controller.rb, client/js/_admin/actions/sites.js, client/js/_admin/components/application_instances/modal.jsx, client/js/_admin/components/lti_installs/index.jsx, client/js/_admin/components/sites/delete_form.jsx, client/js/_admin/components/sites/delete_form.spec.jsx, client/js/_admin/components/sites/delete_modal.jsx, client/js/_admin/components/sites/delete_modal.spec.jsx, client/js/_admin/components/sites/form.jsx, client/js/_admin/components/sites/form.spec.jsx, client/js/_admin/components/sites/header.jsx, client/js/_admin/components/sites/header.spec.jsx, client/js/_admin/components/sites/index.jsx, client/js/_admin/components/sites/index.spec.jsx, client/js/_admin/components/sites/list.jsx, client/js/_admin/components/sites/list.spec.jsx, client/js/_admin/components/sites/modal.jsx, client/js/_admin/components/sites/modal.spec.jsx, client/js/_admin/components/sites/site_row.jsx, client/js/_admin/components/sites/site_row.spec.jsx, client/js/_admin/reducers/site_to_oauth.js, client/js/_admin/reducers/sites.js, client/js/_admin/routes.jsx, client/styles/admin/partials/_btn.scss, client/styles/admin/partials/_modal.scss, config/initializers/apartment.rb, spec/controllers/api/sites_controller_spec.rb
Add ability to edit sites from index
Add ability to create/delete sites
Add specs for all sites components
Add rspecs for sites controller
Set Site as a global apartment
=> Add Sites index

client/js/_admin/components/application_instances/index.jsx, client/js/_admin/components/common/heading.jsx, client/js/_admin/components/common/heading.spec.jsx, client/js/_admin/components/common/sub_nav.jsx, client/js/_admin/components/common/sub_nav.spec.jsx, client/js/_admin/components/layout/index.jsx, client/js/_admin/components/layout/index.spec.jsx, client/js/_admin/components/lti_installs/index.jsx, client/js/_admin/routes.jsx, client/styles/admin/partials/_head.scss, client/styles/admin/partials/_objects.scss
This sub nav is temporary until we can implement a better sidebar.
Fixes back button to use Links instead of history.goBack().
Fixes sites route to not be nested with applications so nave is-active works correctly.
=> Add sub nav and fix back button

client/js/_admin/components/lti_installs/index.jsx, client/js/_admin/components/lti_installs/install_pane.jsx, client/js/_admin/components/lti_installs/install_pane.spec.jsx, client/js/_admin/components/lti_installs/sidebar.jsx, client/js/_admin/components/lti_installs/sidebar.spec.jsx, client/styles/admin/partials/_info.scss, client/styles/admin/partials/_inputs.scss, client/styles/admin/partials/_sidebar.scss
Filters to only show courses that have installed the current tool.
=> Add filter checkbox to filter courses.

app/models/oauth_state.rb, spec/models/application_spec.rb, spec/models/authentication_spec.rb, spec/models/oauth_state_spec.rb, spec/models/site_spec.rb
Single line validates state for OauthState
=> Add several rspecs

README.md, app/controllers/api/application_instances_controller.rb, app/models/application.rb, app/models/application_instance.rb, client/js/_admin/components/application_instances/form.jsx, db/migrate/20170406181303_add_visibility_to_application_instance.rb, db/schema.rb, lib/lti/config.rb, lib/lti/utils.rb
Defaults visibility to `public`
https://www.pivotaltracker.com/story/show/143335219
=> Make visibility configurable.

app/controllers/api/canvas_proxy_controller.rb, app/views/admin/home/index.html.erb, client/config/settings.js
Fix canvas proxy to return json
Fix admin index webpack bundles
Remove hotPort from devAssetsUrl
=> Fix random things

app/models/application_instance.rb, client/apps/admin/package.json
=> Fix loading domain for lti_config

app/helpers/application_helper.rb
=> Cache the canvas_url

app/controllers/application_controller.rb
* Removes final remnants of disabled app
=> Remove Disabled App Remnants

app/controllers/concerns/jwt_token.rb, app/lib/auth_token.rb, app/models/authentication.rb, db/migrate/20170705132718_add_authentication_token_to_authentication.rb, db/schema.rb
Add secure id_token to authentications
Add ability to pass in secret and aud to issue a jwt
Add method to validate jwt with custom aud and secret and also not sign anyone in
=> Refactor some authentication code

app/models/application_instance.rb, app/models/site.rb, db/seeds.rb, spec/factories/applications.rb, spec/models/application_instance_spec.rb
* Generates LTI Key specifically for site and application
=> Generate lti key

db/migrate/20170711215536_add_index_to_app_instance.rb, db/schema.rb, db/seeds.rb
* Add index to app instances on lti_key
=> Fix seeds to find correct app instance

app/controllers/omniauth_callbacks_controller.rb, app/views/shared/_omniauth_error.html.erb, config/initializers/apartment.rb, config/initializers/devise.rb, db/seeds.rb
Redirect to oauth error page when an oauth error occurs
=> Redirect to oauth error page

app/controllers/application_controller.rb, app/controllers/concerns/canvas_support.rb, app/models/application.rb, app/models/application_bundle.rb, app/models/application_instance.rb, app/models/bundle_instance.rb, db/migrate/20170731160737_create_bundle_instance.rb, db/schema.rb, db/seeds.rb, spec/factories/bundle_instance.rb, spec/factories/bundles.rb
* Adds BundleInstance to support welcome process for multiple apps (I.E. Installing AtomicCMS actually installs several lti tools)
=> Add Bundle Instance

app/models/bundle_instance.rb, spec/models/bundle_instance_spec.rb
Add before_save filter to fix entity_key before save
=> Adds fix_entity_key to bundle_instance

app/controllers/application_controller.rb, app/controllers/concerns/canvas_support.rb, app/models/application_instance.rb, app/models/authentication.rb, app/models/canvas_course.rb, app/models/user.rb, db/migrate/20170926191503_create_canvas_courses.rb, db/migrate/20170926200235_add_auth_to_app_instance_and_course.rb, db/schema.rb, spec/factories/_common.rb, spec/factories/canvas_courses.rb, spec/models/canvas_course_spec.rb
Add canvas course model
Support application instances and canvas course to have many authentications
Update canvas support to lookup an auth based on application instance or canvas course
Support being able to copy users and courses and authentications across tenants
=> Backport changes

app/models/authentication.rb, db/migrate/20171003181935_change_lti_integer_to_bigint.rb, db/schema.rb
Changes integer to bigint in database schema
=> Merge upstream

app/models/authentication.rb, app/models/canvas_course.rb, spec/models/authentication_spec.rb, spec/models/canvas_course_spec.rb
=> Update copy_to_tenant auth to work with users

app/controllers/api/application_instances_controller.rb
* Set application instance domain automatically in model
=> Fix admin tool

client/apps/admin/components/lti_installs/install_pane.jsx, client/apps/admin/components/lti_installs/install_pane.spec.jsx
* Adds ability to search all courses from navigator search
=> Admin Tool All Course Search

app/controllers/concerns/canvas_support.rb, app/helpers/application_helper.rb, app/helpers/oauth_helper.rb
Move oauth_host into new oauth helper
=> Add oauth helper

app/controllers/concerns/jwt_token.rb, spec/controllers/concerns/jwt_token_spec.rb, spec/factories/users.rb
* Adds jwt_lti_roles_string helper method
* Change jwt_lti_roles to always return an array
=> Fix Nil Jwt Error

client/apps/admin/components/lti_installs/install_pane.jsx, client/apps/admin/reducers/courses.js
Call loadExternalTools on appropriate courses
Remove useless external_tools assignment
=> Fix ability to install into a course

app/controllers/concerns/content_item_support.rb, client/apps/hello_world/actions/content_items.spec.js, client/apps/hello_world/actions/lti_launches.js, client/apps/hello_world/actions/lti_launches.spec.js
* Adds additional actions and tests to support content item
* Adds ability to specify application_instance when setting up a content item response.
=> Content item

app/controllers/application_controller.rb
If the first param was NULL, then it would create a race condition.
=> Fix sql race condition

config/initializers/apartment.rb
So we can add more models downstream
=> Multiline apartment excluded models

.rubocop.yml, Gemfile.lock
=> Update rubocop to 0.53.0

app/controllers/api/ims_imports_controller.rb, app/jobs/ims_import_job.rb, config/environments/test.rb, spec/controllers/api/ims_imports_controller_spec.rb, spec/jobs/ims_import_job_spec.rb
Set test env active_job adapter to :test
Use rails 5.1 strong param for allowing arbitrary values in a hash
=> Move ims_import to ActiveJob

config/initializers/apartment.rb
Find the auth domain first
Then find by the lti key
=> Rearrange the apartment selectors

app/controllers/concerns/storage_support.rb, app/lib/exceptions.rb
To move files to tmp directories
=> Add storage support

app/lib/lti/request.rb, app/lib/middleware/oauth_state_middleware.rb, app/views/shared/_default_client_settings.html.erb, spec/lib/lti/request_spec.rb
Add ability to load oauth_consumer_key from session as well
=> Add oauth_consumer_key to oauth request env

app/controllers/api/ims_imports_controller.rb, spec/controllers/api/ims_imports_controller_spec.rb
This change makes downstream apps able to verify separate data is present
=> Verify ims import data params separately

app/lib/lti/config.rb, config/initializers/devise.rb, spec/lib/lti/config_spec.rb
uses the custom api domain variable substitution for oauth.
=> fixes the vanity domain issue

app/controllers/omniauth_callbacks_controller.rb
Set the lti_provider from the provider_url attribute and not the json_response
=> Set the lti_provider from the provider_url attribute

app/views/layouts/_show_environment.erb, config/secrets.example.yml
Add secret to switch env banner on
=> Only display environment when wanted

app/middleware/requests_logger.rb, app/models/request_log.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/apartment.rb, db/migrate/20190313033308_create_request_logs.rb, db/schema.rb, spec/factories/_common.rb, spec/factories/request_logs.rb, spec/models/request_log_spec.rb
Logs each request to the database
Provides scopes for retrieving the data later
=> Add requests logger middleware

app/middleware/requests_logger.rb
Remove the use of the quoting as it isn't needed.
=> Use binds instead of interpolating

app/controllers/api/application_instances_controller.rb, spec/controllers/api/application_instances_controller_spec.rb
Also delete request statistics.
=> Delete tenant when application instance is deleted

app/controllers/api/application_instances_controller.rb
Re-use code to load app instances
Fixes loading single app instance to also include request stats
=> Refactor loading app instances

client/apps/admin/reducers/application_instances.js
Fix when updating or deleting an app instance
=> Fix app instance reducer

Gemfile, Gemfile.lock, app/models/que_job.rb, config/application.rb, db/migrate/20190603162353_add_que.rb, db/schema.rb
Add que gem and apartment-activejob-que gem
Add QueJob model
Set que to be the queue_adapter
Add migration for que job data
=> Backport que backend worker

.gitlab-ci.yml
Adds linter
Adds rspec
Adds jest
Adds dependency scanning
Adds sast
=> Add gitlab ci yaml

client/apps/admin/components/application_instances/__snapshots__/form.spec.jsx.snap, client/apps/admin/components/application_instances/form.jsx, client/apps/admin/package.json, yarn.lock
Upgrade from 1.2.1 to 3.0.4
Fix component to be compatible with new version.
=> Upgrade react-select package

app/controllers/concerns/lti_support.rb
Check that lms_user_id is present before loading by lms_user_id
=> Fix loading user from lti

Gemfile, Gemfile.lock, app/controllers/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/shared/_default_admin_client_settings.html.erb, client/apps/admin/components/common/heading.jsx, config/initializers/devise.rb, config/secrets.example.yml, spec/factories/_common.rb, spec/models/user_spec.rb
Require better passwords for admins.
=> Implement better password requirements

package.json
The official jest docs say to use `<rootDir>` instead of `./`. https://jestjs.io/docs/en/webpack
=> Fix jest config <rootDir> issue

app/controllers/omniauth_callbacks_controller.rb, app/models/user.rb
Increase generated password length to 72 characters.
=> Increase generated password strength

app/controllers/api/application_instances_controller.rb, app/models/request_statistic.rb, app/models/request_user_statistic.rb, client/apps/admin/components/application_instances/__snapshots__/list_row.spec.jsx.snap, client/apps/admin/components/application_instances/list_row.jsx
The other scope extend it. People keep asking for yearly stats in act, this makes it easier to pull those.
=> create a flexible for_n_days scope on stats models,

app/controllers/api/lti_install_keys_controller.rb, client/apps/admin/actions/lti_install_keys.js, client/apps/admin/components/applications/__snapshots__/application_row.spec.jsx.snap, client/apps/admin/components/applications/__snapshots__/index.spec.jsx.snap, client/apps/admin/components/applications/application_row.jsx, client/apps/admin/components/applications/index.jsx, client/apps/admin/components/lti_install_keys/form.jsx, client/apps/admin/components/lti_install_keys/form.spec.jsx, client/apps/admin/components/lti_install_keys/header.jsx, client/apps/admin/components/lti_install_keys/header.spec.jsx, client/apps/admin/components/lti_install_keys/index.jsx, client/apps/admin/components/lti_install_keys/index.spec.jsx, client/apps/admin/components/lti_install_keys/list.jsx, client/apps/admin/components/lti_install_keys/list.spec.jsx, client/apps/admin/components/lti_install_keys/list_row.jsx, client/apps/admin/components/lti_install_keys/list_row.spec.jsx, client/apps/admin/components/lti_install_keys/modal.jsx, client/apps/admin/components/lti_install_keys/modal.spec.jsx, client/apps/admin/reducers/index.js, client/apps/admin/reducers/lti_install_keys.js, client/apps/admin/reducers/lti_install_keys.spec.js, client/apps/admin/routes.jsx, config/routes.rb, spec/controllers/api/lti_install_keys_controller_spec.rb, spec/factories/lti_installs.rb
=> Add components to create/update/delete lti install records

app/controllers/api/lti_install_keys_controller.rb, client/apps/admin/actions/lti_install_keys.js, client/apps/admin/reducers/lti_install_keys.js, client/apps/admin/reducers/lti_install_keys.spec.js, spec/controllers/api/lti_install_keys_controller_spec.rb
=> Remove extraneous code

app/lib/lti_advantage/authorization.rb, app/lib/lti_advantage/services/names_and_roles.rb, spec/lib/lti_advantage/services/names_and_roles_spec.rb
This fixes a few small bugs related to LTI Advantage.
Please review the commit messages for details on each change.
=> Fix a Few LTI Advantage Bugs

bin/bootstrap
Only delete the files if the arg --force is passed in.
Only create the files they don't exist.
Print a message to the screen when creating a file.
=> Update bin/bootstrap to respect existing files

.env.example
=> Fixed the default app subdomain (should be helloworld.atomicjolt.xyz)

app/controllers/omniauth_callbacks_controller.rb, client/apps/admin/components/application_instances/__snapshots__/list_row.spec.jsx.snap, client/apps/admin/components/application_instances/list_row.jsx, spec/controllers/omniauth_callbacks_controller_spec.rb
Build the expected url and check the result against what is sent in.
If they don't match, render the omniauth error page with a message stating bad uri.
=> Update oauth redirect to check url first

config/initializers/active_job.rb
Adds initializer specified in the README of https://github.com/bfcoder/apartment-activejob.
=> Adds intializer for Apartments and Active Jobs

app/controllers/omniauth_callbacks_controller.rb, spec/controllers/omniauth_callbacks_controller_spec.rb
Remove redirect, just render the error page.
If redirect is still needed, hunt Justin down. :]
=> Simplify omniauth error message

.gitlab-ci.yml
We switched from eslint_npm to eslint
=> Fix pronto eslint command

.github/workflows/github-actions-ci-rspec.yml, spec/lib/lti/config_spec.rb
=> Test with multiple ruby versions

app/controllers/concerns/lti_support.rb, app/lib/lti_advantage/lti_user.rb
We have zero need to store real email addresses.
Always generate the email address now.
=> Stop storing emails

db/lti_advantage_configs/hello_world_lti_advantage_config.json, lib/tasks/canvas.rake
* Rake task for updating lti advantage install with lti 1.1 key / secret to authenticate import / export hooks
* Add import / export hook url to lti advantage json template
=> LTI Advantage Import / Export Support

app/controllers/concerns/jwt_token.rb, app/controllers/concerns/lti_support.rb
Prevents user from being stored on session for 
* Jwt Token Auth
* Lti Launch
=> Dont store user on session

client/apps/admin/components/application_instance_settings/lti_install_selector.jsx, client/apps/admin/components/application_instances/__snapshots__/form.spec.jsx.snap, client/apps/admin/components/application_instances/__snapshots__/index.spec.jsx.snap, client/apps/admin/components/application_instances/__snapshots__/modal.spec.jsx.snap, client/apps/admin/components/application_instances/form.jsx, client/apps/admin/components/application_instances/index.jsx, client/apps/admin/components/application_instances/index.spec.jsx, client/apps/admin/components/application_instances/modal.jsx, client/apps/admin/components/applications/application_row.jsx, client/apps/admin/components/applications/index.jsx, client/apps/admin/components/lti_install_keys/__snapshots__/form.spec.jsx.snap, client/apps/admin/components/lti_install_keys/form.jsx, client/apps/admin/components/lti_install_keys/index.jsx, client/apps/admin/components/lti_install_keys/list_row.jsx, client/apps/admin/components/lti_install_keys/modal.jsx, client/apps/admin/components/lti_installs/course_installs.jsx, client/apps/admin/components/lti_installs/index.jsx, client/apps/admin/components/sites/__snapshots__/form.spec.jsx.snap, client/apps/admin/components/sites/__snapshots__/modal.spec.jsx.snap, client/apps/admin/components/sites/__snapshots__/site_row.spec.jsx.snap, client/apps/admin/components/sites/form.jsx, client/apps/admin/components/sites/modal.jsx, client/common/components/account_analytics/account_graphs.jsx
=> Tl fixing refactor
