- client/js/_admin/components/application_instances/form.jsx
- client/js/_admin/components/application_instances/form.spec.jsx
Previously they were not getting assigned the same name. Thus you could select all 3 types. The next problem was the value wasn't getting set to anything. This fixes both issues.
> Fix form to correctly set lti_type radio buttons.

- app/controllers/api/application_instances_controller.rb
- client/js/_admin/actions/application_instances.js
- client/js/_admin/components/application_instances/form.jsx
- client/js/_admin/components/application_instances/index.jsx
- client/js/_admin/components/application_instances/index.spec.jsx
- client/js/_admin/components/application_instances/input.jsx
- client/js/_admin/components/application_instances/list.jsx
- client/js/_admin/components/application_instances/list.spec.jsx
- client/js/_admin/components/application_instances/list_row.jsx
- client/js/_admin/components/application_instances/list_row.spec.jsx
- client/js/_admin/components/application_instances/modal.jsx
- client/js/_admin/components/application_instances/modal.spec.jsx
- spec/controllers/api/application_instances_controller_spec.rb
- spec/controllers/api/applications_controller_spec.rb
Adds cog to each app instance row.
Opens modal to edit it.
Canvas Token will be empty as that is a salted field in the database.
No longer can edit lti key
> Add ability to update app instances

- client/js/_admin/components/lti_installs/install_pane.jsx
- client/js/_admin/components/lti_installs/install_pane.spec.jsx
Only show account installs for basic/account_navigation types.
Only show course installs for basic/course_navigation types.
Add specs for install pane.
Will need additional designs if more than this is desired.
With default message for account navigation tools
With default message for course navigation tools
> Only show account/course installs where appropriate.

- app/models/application_instance.rb
- config/initializers/apartment.rb
- spec/models/application_instance_spec.rb
This fixes running `rake db:setup` multiple times.
On subsequent runnings of `rake db:setup` the tenants will not
be deleted and thus it causes errors when trying to create
a tenant that already exists.
* Process after_commit to ensure the model is persisted before attempting to create the tenant schema.
* Refactored `.try` to use new short notation of `&.`
* Refactored creating lti_secret to use shorthand notation `||=`
* Refactored `create_schema` to rescue `Apartment::TenantExists` and do nothing
* Fix bug where tenants were created using `lti_key` instead of `tenant`
* Refactor `tenant_names` to be uniq now that `tenant` is used to create Tenants
* Remove after_destroy callback to ensure databases aren't destroyed
* Refactor `destroy_schema` to be a private method to ensure it doesn't …
> Fix creating tenants from application instances

- client/js/libs/canvas/middleware.js
fixes bug causing promise to not resolve and not dispatch to reducer is there was an error during the canvas request.
> adds error condition to canvas middleware

- client/js/_admin/components/lti_installs/install_pane.jsx
Previously, they were only loaded one time for a given set of courses.
But if more courses were loaded into the page later, their external tools were never loaded.
This ensures that all courses on the page will have external tools loaded.
> Load external tools reliably for courses

- app/controllers/concerns/lti_support.rb
- spec/controllers/concerns/lti_support_spec.rb
This fixes a situation where an lti user is attempted to be created with the same email as an existing user in the database. `domain` is now passed in to the generate unique email address method.
> Pass domain to attempt unique email address

- app/controllers/api/application_instances_controller.rb
- app/controllers/api/applications_controller.rb
- app/models/application.rb
- app/models/application_instance.rb
- app/serializers/hash_serializer.rb
- client/js/_admin/actions/application_instances.js
- client/js/_admin/actions/applications.js
- client/js/_admin/components/application_instances/form.jsx
- client/js/_admin/components/application_instances/form.spec.jsx
- client/js/_admin/components/application_instances/modal.jsx
- client/js/_admin/components/applications/form.jsx
- client/js/_admin/components/applications/form.spec.jsx
- client/js/_admin/components/applications/modal.jsx
- client/js/_admin/components/common/textarea.jsx
- client/js/_admin/components/common/textarea.spec.jsx
- client/js/_admin/components/common/warning.jsx
- client/js/_admin/components/common/warning.spec.jsx
- client/js/_admin/reducers/application_instances.js
- client/js/_admin/reducers/applications.js
- config/environments/test.rb
- db/migrate/20170309132554_add_default_config_to_application.rb
- db/schema.rb
- db/seeds.rb
- spec/models/application_instance_spec.rb
* Add configs to application and application_instance in the database
* Add serializer for configs
* Can now access model.foo instead of model.config[:foo]
* Ensure new app instance copies the default config from an app if it is blank
* Add example to seeds
* Add UI to edit default config for applications
* Add UI to edit config for app instance
* Add/update specs
> Add configs to application and application_instance

- client/js/_admin/components/lti_installs/course_install_row.jsx
- client/js/_admin/components/lti_installs/course_install_row.spec.jsx
Link goes to course in a new tab. If the tool is installed to the course, it takes you to the external tool page. https://www.pivotaltracker.com/story/show/141273415
> Add course links to course install

- client/js/_admin/components/application_instances/config_xml_modal.jsx
- client/js/_admin/components/application_instances/config_xml_modal.spec.jsx
- client/js/_admin/components/application_instances/list.jsx
- client/js/_admin/components/application_instances/list_row.jsx
https://www.pivotaltracker.com/story/show/141273517
> Add a modal that displays the lti xml config for that instance.

- app/controllers/concerns/canvas_support.rb
- client/libs/middleware/api.js
This makes it possible to authorize actions that don't have a type passed in.
> Refactor protect_canvas_api to accept keyword arguments

- CHANGES.md
- app/controllers/api/lti_launches_controller.rb
- app/lib/middleware/oauth_state_middleware.rb
- app/views/shared/_default_admin_client_settings.html.erb
- app/views/shared/_default_client_settings.html.erb
- client/apps/admin/components/application_instances/form.jsx
- client/apps/admin/components/sites/modal.jsx
- config/initializers/apartment.rb
- config/initializers/omniauth.rb
- config/secrets.example.yml
- spec/lib/middleware/oauth_state_middleware_spec.rb
Channels all OAuth requests through a single domain. The applications root domain will be used in combination with
the value defined by "oauth_subdomain" in secrets.yml. i.e. <oauth_subdomain>.<application_root_domain>
> Channel all OAuth requests through a single domain

- app/models/bundle_instance.rb
- spec/models/bundle_instance_spec.rb
A site can have instances of many bundles, who all share the same entity key. So the entity_key cannot be unique.
> Remove uniqueness constraint on BundleInstance.entity_key

- app/controllers/api/canvas_proxy_controller.rb
- app/controllers/concerns/canvas_support.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
Refactor canvas_api so user can be passed in, defaults to current_user
Separate global and user auth into methods that can be called
BREAKING CHANGE: canvas_auth now accepts a site and user
Add a routes default url host to environments
> Refactor canvas support

- app/controllers/concerns/lti_support.rb
We obtain the LTI user id during the Oauth process but not a related lti provider id. We need to be able to find the user during the LTI launch so we are removing the requirement that the provider match - each LTI tool is scoped to it's own tenant so we shouldn't have to worry about collisions.
> Don't use provider to find LTI user - lti user id is sufficient

- app/controllers/concerns/canvas_support.rb
- app/helpers/application_helper.rb
- app/views/shared/_default_admin_client_settings.html.erb
- app/views/shared/_default_client_settings.html.erb
This resolves a problem if you have several subdomains you want to use. ie:
If you have 
```
my.great.app.com
```
Previously it would generate
```
auth.app.com
```
but now the oauth callback url can be
```
auth.my.great.app.com
```
> Update the oauth callback urls to accept a host with multiple subdomains

- app/controllers/api/jwts_controller.rb
When a JWT is refreshed, we currently loose all the custom data that was added to it.
This fixes it so all existing data is kept in the refreshed JWT.
> Refresh JWT with existing jwt data

- tests.sh
Fixes yarn test warning:
```
No tests found
In /Users/jamescarbine/Documents/projects/lti_starter_app/client
178 files checked.
testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 57 matches
testPathIgnorePatterns: /node_modules/,/apps/ - 2 matches
```
> Remove extra yarn test

- app/controllers/concerns/lti_support.rb
- app/controllers/omniauth_callbacks_controller.rb
Move skip confirm to exactly after user is created in memory.
This avoids in the downstream apps from adding code before the skip confirm that saves the user to the database.
> Fix skip confirm

- app/controllers/api/ims_exports_controller.rb
- app/controllers/concerns/canvas_imscc_support.rb
- app/helpers/jwt_helper.rb
- app/models/application_instance.rb
- config/initializers/apartment.rb
- spec/controllers/concerns/canvas_imscc_support_spec.rb
- spec/models/application_instance_spec.rb
* Don’t use a dasherized domain of `site.key-application.key` and use just the `application.key`
* Update Apartment to function with just the consumer key and not the domain the request comes in on.
* This allows backwards compatibility with dasherized subdomains
* Pull the consumer key out of the jwt via the `kid` attribute.
> Support single domains for application instances

- app/controllers/api/ims_imports_controller.rb
- spec/controllers/api/ims_imports_controller_spec.rb
Before processing lti_launches in an ims_import, ensure they actually
exist first.
> Ensure lti_launches exist

- app/controllers/api/application_instances_controller.rb
- app/models/application_instance.rb
- spec/controllers/api/application_instances_controller_spec.rb
This fixes the admin tool displaying app instances in seemingly random order.
> Order application instances by the oldest

- app/middleware/requests_logger.rb
If a request hits the site and there isn't a logged in user, default to user_id 0
> Fix logger for non-logged-in requests

- app/controllers/api/application_instances_controller.rb
- client/apps/admin/actions/application_instances.js
- client/apps/admin/components/application_instances/__snapshots__/list.spec.jsx.snap
- client/apps/admin/components/application_instances/index.jsx
- client/apps/admin/components/application_instances/list.jsx
- client/apps/admin/components/common/sortable.jsx
- client/apps/admin/components/lti_installs/index.jsx
- client/apps/admin/reducers/application_instances.js
- client/apps/admin/reducers/application_instances.spec.js
- client/apps/admin/styles/partials/_tables.scss
- spec/controllers/api/application_instances_controller_spec.rb
Make it sortable on lti_key and on created_at
Use an array to store data to preserve order
> Add sortable columns to admin tool

- app/middleware/requests_logger.rb
Match any request path that starts with /lti_launches
ie: `"/lti_launches/ga4NE8qBEzzDo1ycz3ycJ23y"`
> Fix lti launch requests

- app/jobs/application_job.rb
Backport - Add a default queue
Backport - Set the rollbar scope
Set the max retry for que to 17 (effectively 3.8 days of attempting), then delete the job.
> Improve the base ApplicationJob

- spec/controllers/api/application_instances_controller_spec.rb
- spec/controllers/api/applications_controller_spec.rb
- spec/controllers/api/canvas_proxy_controller_spec.rb
- spec/controllers/api/ims_exports_controller_spec.rb
- spec/controllers/api/ims_imports_controller_spec.rb
- spec/controllers/api/lti_content_item_selection_controller_spec.rb
- spec/controllers/api/lti_launches_controller_spec.rb
- spec/controllers/api/sites_controller_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/concerns/canvas_imscc_support_spec.rb
- spec/controllers/concerns/canvas_support_spec.rb
- spec/controllers/concerns/content_item_support_spec.rb
- spec/controllers/concerns/iframe_support_spec.rb
- spec/controllers/concerns/lti_support_spec.rb
- spec/controllers/lti_launches_controller_spec.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/jobs/ims_export_job_spec.rb
- spec/lib/integrations/canvas_api_support_spec.rb
- spec/lib/middleware/oauth_state_middleware_spec.rb
- spec/rails_helper.rb
- spec/support/application_instance_helper.rb
- spec/support/cleaner.rb
- spec/support/common.rb
This adds a helper that creates an application instance once at the beginning of the test suite instead of for every test. I mostly would like to be able to use it in our downstream projects.
> Speed up specs

- spec/controllers/application_controller_spec.rb
- spec/controllers/concerns/lti_support_spec.rb
- spec/support/common.rb
The changes from https://github.com/atomicjolt/lti_starter_app/pull/303 made one of the application controller helper method specs just test the mocked current_application_instance, not actually test the method.
> Fix bad spec I introduced

- app/controllers/concerns/lti_support.rb
If it's not available we should leave the value null. Setting it to the user_id from params puts the LTI user id into the field which is not the same as the lms_user_id and results in inconsistent behavior.
> Don't use user_id from LTI launch for lms_user_id

- package.json
This is a problem downstream where we import json files, we don't want
to transform json files.
> Only transform jsx

- spec/controllers/api/sites_controller_spec.rb
Rails 6 will be removing success? and it is replaced with successful?
rspec now has a be_successful that uses the correct predicate.
> Change be_success -> be_successful

- app/controllers/api/application_instances_controller.rb
- app/controllers/api/applications_controller.rb
- app/lib/integrations/canvas_api_support.rb
- app/models/application_instance.rb
- client/apps/admin/components/application_instances/__snapshots__/form.spec.jsx.snap
- client/apps/admin/components/application_instances/form.jsx
- client/apps/admin/components/applications/__snapshots__/form.spec.jsx.snap
- client/apps/admin/components/applications/form.jsx
- client/apps/admin/components/applications/modal.jsx
- db/migrate/20200219210631_move_application_instance_developer_keys.rb
- db/schema.rb
This moves developer keys from application instances to applications. This will let us have application level global keys, and if needed we can have canvas instance level keys as well, although those will have to be shared across all applications.
> Move developer keys from application instances to applications

- app/controllers/api/application_instances_controller.rb
Because both site and application instance have oauth_key and oauth_secret methods this would have continued to work unless the application had a different oauth key and secret than the site. Then if the token was originally created from the application oauth key it would fail to refresh.
> Fix sending the site instead of the application instance after moving oauth keys to applications and sites.

- db/migrate/20200226194920_default_scoped_developer_key_off.rb
- db/schema.rb
We don't want to always send the scopes, only send them when specifically enabled.
> Alter default value for whether to use scopes when oauthing with Canvas

- app/lib/lti_advantage/definitions.rb
- db/seeds.rb
This branch adds constants for each role specified in the [LTI 1.3 spec](https://www.imsglobal.org/spec/lti/v1p3#role-vocabularies-0).
I think it will be helpful to have a definitive list of all LTI 1.3 roles and have them set in constants so we can reference the constants instead of having multiple instances of roles as strings throughout the codebase.
> Add LTI 1.3 Roles to Definitions

- app/controllers/application_controller.rb
- app/controllers/omniauth_callbacks_controller.rb
- app/views/shared/_default_client_settings.html.erb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/support/lti_advantage_helper.rb
If a user needed to authorize with Canvas before using the application, the application would fail with an internal server error after authorizing. If you refreshed the page, the application would launch correctly but not immediately after authorizing.
This was happening because the authorization flow wasn't setting some necessary LTI 1.3 values.
This branch adds those values and the application runs correctly after authorizing with Canvas. No page refresh needed.
> Set LTI 1.3 Launch Values After Authorizing with Canvas 

- db/seeds.rb
While Canvas usually provides this for us without us needing to ask for it, in content item select launches it will not, resulting in users that temporarily do not have a lms user id until they launch normally.
> Get the user id as a variable substitution

- Gemfile
- app/controllers/concerns/deep_linking.rb
- app/controllers/concerns/open_id_connect_support.rb
- app/lib/lti_advantage/authorization.rb
- app/models/application.rb
- app/models/application_instance.rb
- app/models/lti_deployment.rb
- app/models/lti_install.rb
- db/migrate/20200624153201_add_lti_install_id_to_lti_deployments.rb
- db/schema.rb
- spec/controllers/concerns/open_id_connect_support_spec.rb
- spec/controllers/lti_launches_controller_spec.rb
- spec/factories/_common.rb
- spec/factories/lti_deployments.rb
- spec/factories/lti_installs.rb
- spec/lib/lti_advantage/authorization_spec.rb
- spec/models/application_instance_spec.rb
- spec/models/application_spec.rb
- spec/models/ims_export_spec.rb
- spec/models/lti_deployment_spec.rb
- spec/support/lti_advantage_helper.rb
Currently, the application has some incorrect logic that doesn't allow having multiple `LtiInstall` records with the same `iss`. When there are two `LtiInstall` records with the same `iss`, the most recent `LtiInstall` record's `client_id` is always used. This means that only deployments associated with the most recent `LtiInstall` with that `iss` can be launched or embedded. This branch makes the necessary changes to allow multiple `LtiInstall`s with the same `iss`.
We addressed the above problem by making the `LtiDeployment` model a child of `LtiInstall`. This will give us access to the `client_id` in a few different contexts where we need it. Right now, we're finding the `client_id` by looking up the `LtiInstall` with the `iss`. This isn't a dependable way to get a `client_id` though …
> Support Multiple LTI Installs with the Same `iss` 

- app/controllers/concerns/lti_support.rb
- spec/controllers/concerns/lti_support_spec.rb
We validate the email on an LTI request. We don't actually need a valid email. Bookshark put in all bogus emails and they weren't able to launch our tool. If we detect a bad email we just generate an anonymous value and move along. Everyone can be happy now.
> If the student email is invalid they receive a 500 error

- app/lib/lti_advantage/services/names_and_roles.rb
This gives an error message when the names and roles list is called and the LTI key is set to private.
> Added error message for when LTI key is set to private

- app/controllers/application_controller.rb
- app/controllers/concerns/lti_support.rb
- app/lib/lti_advantage/definitions.rb
- app/lib/lti_advantage/params.rb
- app/views/shared/_default_client_settings.html.erb
- db/seeds.rb
makes a couple of improvements to lti advantage param handling.
1) It adds a class that wraps the params we receive from Canvas and
provies convenience methods for accessing different pieces of data.
2) Both the oauth and lti launch controllers now call a
set_lti_advantage_launch_values method for setting instance variables
based on the launch params.
3) Adds a simple helper function to check if the current launch is lti
advatage, rather than repeating the id_token check, which is less
obvious
Also fixes the seeds, which were broken
> lti params helper

- client/apps/hello_world/styles/modules/_mixins.scss
- client/apps/hello_world_graphql/components/home.spec.jsx
- client/apps/hello_world_graphql/history.js
- client/apps/hello_world_graphql/styles/modules/_mixins.scss
- config/application.rb
This branch updates a few issues that are causing errors to be displayed in the browser console:
* Eliminate invalid "X-Frame-Options" header
* Update deprecated `createHashHistory` import
* Fix incorrect path to fonts
Please see the individual commit messages for more details on each fix.
> Fix Console Errors

- config/environments/production.rb
Use admin subdomain so invitations have the correct url to setup your
account with.
> Update default mailer url host

- app/lib/lti_advantage/services/names_and_roles.rb
- spec/lib/lti_advantage/services/names_and_roles_spec.rb
This branch just makes a couple of improvements to the error we raise when it looks like the user's LTI key is set to private.
> Improve LTI Key Error

- app/lib/lti_advantage/services/names_and_roles.rb
- spec/lib/lti_advantage/services/names_and_roles_spec.rb
We recently added some code the the names and roles class that we extracted from Atomic Journals. We failed to generalize that code fully though and some of the naming and messaging was specific to Atomic Journals; it didn't make sense in the general context of the starter app.
This branch modifies and removes that out of place wording.
> Improve Wording in Names and Roles Service

- app/controllers/application_controller.rb
- app/models/application_instance.rb
- app/views/errors/400.html.erb
- app/views/errors/401.html.erb
- app/views/errors/403.html.erb
- app/views/errors/404.html.erb
- app/views/errors/422.html.erb
- app/views/errors/500.html.erb
- app/views/layouts/errors.html.erb
Copy all error pages into views. Customize 500 page to add an optional custom error message.
Leaving public error pages intact. As they can still be used (like routing errors).
> Add ability to display custom error message on 500 page

- bin/setup
- bin/setup-linux
nginx deprecated the `ssl on;` directive in favor of `listen *443 ... ssl`, this PR updates those in the setup and setup-linux scripts
> updated nginx ssl syntax

- app/lib/exceptions.rb
In `app/controllers/api/graphql_controller.rb` on line 24, we raise an `Exceptions::UnAuthorizedGraphQLCanvasRequest` error. However, this exception class isn't defined.
> Add Definition for Custom Exception Class

- app/lib/lti_advantage/definitions.rb
- app/lib/lti_advantage/services/line_items.rb
- spec/support/webmock_requests.rb
Adds a `LtiAdvantage::Definitions` definition for the Canvas Submission extension: `https://canvas.instructure.com/lti/submission_type`. Replaces all previous references to that with the new constant
> added CANVAS_SUBMISSION_TYPE to Definitions

- app/controllers/lti_launches_controller.rb
- db/migrate/20210210195029_add_resource_link_id_to_lti_launches.rb
- db/schema.rb
- spec/controllers/lti_launches_controller_spec.rb
- spec/support/lti_advantage_helper.rb
This purpose of this branch is to start storing the `resource_link_id` associated with an LTI launch. Having the `resource_link_id` should allow us to better support course copy since it gives us more data on where a launch is coming from.
One thing that's worth mentioning is that the `resource_link_id` sent by Canvas when launching an application that's embeded in a page isn't correct. According to Matt, it's a bug in Canvas. In that scenario, the `resource_link_id` isn't helpful because it's the same as the course context ID. However, the `resource_link_id` is still useful for other scenarios such as assignments or external tools added as modules items. It should also be useful for in-page launches in LMSes other than Canvas.
> Store Resource Link ID in LTI Launch Record 

- app/graphql/types/base_input_object.rb
This was missing from the GraphQL types, but it is referenced elsewhere in the app.
> Added missing GraphQL base input type

- app/lib/integrations/canvas_api_support.rb
- config/initializers/omniauth.rb
Specify the host so we get the subdomain included.
Also include the full module path in the canvas_api_support, to keep these two calls consistent.
> Fix oauth callback url

- bin/setup
Instead of using `/usr/local`, we should be using `$(brew --prefix)` to account for alternate homebrew installation locations. The most notable example of this is running homebrew on ARM64, where the default location has been changed to `/opt/homebrew`.
> Update setup to not hardcode `/usr/local`

- config/initializers/nuclear_secrets.rb
- config/secrets.yml.example
The secret_token is no longer used. It's an artifact from rails 3.2 and 4.0.
DEPRECATION WARNING: `secrets.secret_token` is deprecated in favor of `secret_key_base` and will be removed in Rails 6.0.
From the upgrade guide:
```
Rails 4.0 introduces ActiveSupport::KeyGenerator and uses this as a base from which to generate and verify signed cookies (among other things). Existing signed cookies generated with Rails 3.x will be transparently upgraded if you leave your existing secret_token in place and add the new secret_key_base
```
> Remove old secret_token

- config/environments/production.rb
With rails 6.1 this hack no longer works as the autoloader doesn't load model data in this file anymore. We will just set the host in the secrets now.
> Switch action mailer default host to 100% secret based

- app/jobs/ims_export_job.rb
- app/jobs/ims_import_job.rb
Que will currently not process all queues by default with rails 6. We have to specify the queue now. So we will use the queue named `default` going forward.
> Remove queues from jobs

- config/initializers/que_time_fix.rb
Time needs to be explicitly parsed now. Que does it only in the newer version 1.0 beta.
> Fix que time parse issue

- app/controllers/application_controller.rb
- app/lib/localization.rb
- app/views/shared/_default_client_settings.html.erb
- client/common/libs/i18n.js
- client/common/libs/moment.js
- db/seeds.rb
- package.json
- yarn.lock
This PR adds i18n support for both the rails app and react client.
The changes were backported from a MR in Socialize's GitLab Repo:
https://gitlab.com/atomicjolt/socialize/-/merge_requests/534
> Add i18n support
